image: ubuntu:focal

stages:
  - build
  - generate

build:
  allow_failure: false
  stage: build
  artifacts:
    expire_in: 3 days
    paths:
      - build/rm_power_manager.elf
      - build/rm_power_manager.hex
  only:
    - stm32h7
  script:
    - export DEBIAN_FRONTEND=noninteractive
    - apt-get update && apt-get -y upgrade && apt-get install -y cmake gcc g++ automake autoconf libtool make build-essential wget
    - wget https://armkeil.blob.core.windows.net/developer/Files/downloads/gnu-rm/9-2020q2/gcc-arm-none-eabi-9-2020-q2-update-x86_64-linux.tar.bz2
    - tar jxf gcc-arm-none-eabi-9-2020-q2-update-x86_64-linux.tar.bz2
    - rm gcc-arm-none-eabi-9-2020-q2-update-x86_64-linux.tar.bz2
    - mv gcc-arm-none-eabi-9-2020-q2-update /builds/dynamicx/rm_power_manager/gcc-arm-none-eabi
    - PATH="$PATH:/builds/dynamicx/rm_power_manager/gcc-arm-none-eabi/bin" && echo $PATH
    - mkdir build && cd build && cmake .. -DCMAKE_BUILD_TYPE=Debug && make -j4
    - ls

generate:
  allow_failure: true
  stage: generate
  artifacts:
    expire_in: 3 days
  only:
    - stm32h7
  dependencies:
    - build
  script:
    - ls -a
    - cd ../
    - ls -a
