image: ubuntu:focal

stages:
  - build
  - deploy

build:
  allow_failure: false
  stage: build
  artifacts:
    expire_in: 10 mins
    paths:
      - .industrial_ci
  only:
    - stm32h7
  script:
    - apt-get install cmake gcc g++ automake autoconf libtool make build-essensial
    - wget https://armkeil.blob.core.windows.net/developer/Files/downloads/gnu-rm/9-2020q2/gcc-arm-none-eabi-9-2020-q2-update-x86_64-linux.tar.bz2
    - tar jxf gcc-arm-none-eabi-9-2020-q2-update-x86_64-linux.tar.bz2
    - rm gcc-arm-none-eabi-9-2020-q2-update-x86_64-linux.tar.bz2
    - mv gcc-arm-none-eabi-9-2020-q2-update gcc-arm-none-eabi
    - PATH="$PATH:/builds/dynamicx/rm_power_manager/gcc-arm-none-eabi/bin" && echo $PATH
    - mkdir build && cd build && cmake .. -DCMAKE_BUILD_TYPE=Debug
    - ls -a

deploy:
  allow_failure: false
  stage: deploy
  artifacts:
    expire_in: 10 mins
    paths:
      - .industrial_ci
  only:
    - stm32h7
  dependencies:
    - build
  script:
    - ls -a
    - cd ../
    - ls -a
