image: docker:git
services:
  - docker:dind

stages:
  - prepare
  - build
  - deploy

prepare:
  allow_failure: false
  stage: prepare
  artifacts:
    expire_in: 1 day
  only:
    - stm32h7
  script:
    - ls -a
    - mkdir -p build_temp

build:
  allow_failure: false
  stage: build
  artifacts:
    expire_in: 1 day
  only:
    - stm32h7
  script:
    - cd build_temp
    - ls -a

deploy:
  allow_failure: false
  stage: deploy
  artifacts:
    expire_in: 1 day
  only:
    - stm32h7
  script:
    - ls -a
    - cd ../
    - ls -a
