image: docker:git
services:
  - docker:dind

stages:
  - prepare
  - build
  - deploy

prepare:
  allow_failure: false
  stage: prepare
  artifacts:
    expire_in: 1 day
  only:
    - stm32h7
  script:
    - apt update && apt upgrade -y
    - apt install -y cmake gcc g++ automake autoconf libtool make
    - ls -a

build:
  allow_failure: false
  stage: build
  artifacts:
    expire_in: 1 day
  only:
    - stm32h7
  script:
    - ls -a
    - mkdir build && cd build
    - cmake ..
    - ls -a

deploy:
  allow_failure: false
  stage: deploy
  artifacts:
    expire_in: 1 day
  only:
    - stm32h7
  script:
    - ls -a
    - cd ../
    - ls -a
