image: docker:git
services:
  - docker:dind

stages:
  - prepare
  - build
  - deploy

prepare:
  allow_failure: false
  stage: prepare
  artifacts:
    paths:
      - ./
    expire_in: 10 mins
  only:
    - stm32h7
  script:
    - apk add --update cmake gcc g++ automake autoconf libtool make wget
    - wget https://armkeil.blob.core.windows.net/developer/Files/downloads/gnu-rm/9-2020q2/gcc-arm-none-eabi-9-2020-q2-update-x86_64-linux.tar.bz2
    - tar jxf gcc-arm-none-eabi-9-2020-q2-update-x86_64-linux.tar.bz2
    - rm gcc-arm-none-eabi-9-2020-q2-update-x86_64-linux.tar.bz2
    - mv gcc-arm-none-eabi-9-2020-q2-update gcc-arm-none-eabi
    - cd gcc-arm-none-eabi
    - PATH="$PATH:gcc-arm-none-eabi/bin"

build:
  allow_failure: false
  stage: build
  artifacts:
    paths:
      - ./
    expire_in: 10 mins
  only:
    - stm32h7
  script:
    - ls -a
    - mkdir build && cd build
    - cmake ..
    - ls -a

deploy:
  allow_failure: false
  stage: deploy
  artifacts:
    expire_in: 1 day
  only:
    - stm32h7
  script:
    - ls -a
    - cd ../
    - ls -a
