name: Compile Firmware

on:
  schedule:
    - cron: '0 0 1,11,20,29 * *'
  push:
    branches:
      - master
  workflow_dispatch:

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Configure Software
        run: |
          sudo apt-get update && sudo apt-get -y upgrade && sudo apt-get install -y cmake gcc g++ automake autoconf libtool make build-essential wget git
          wget -q https://armkeil.blob.core.windows.net/developer/Files/downloads/gnu-rm/10.3-2021.10/gcc-arm-none-eabi-10.3-2021.10-x86_64-linux.tar.bz2
      - name: Install Compiler
        run: |
          tar jxf gcc-arm-none-eabi-10.3-2021.10-x86_64-linux.tar.bz2
          ls
          mv gcc-arm-none-eabi-10.3-2021.10 ./gcc-arm-none-eabi
          rm gcc-arm-none-eabi-10.3-2021.10-x86_64-linux.tar.bz2
      - name: Configure CMake
        run: |
          PATH="$PATH:/home/runner/work/rm_power_manager/rm_power_manager/gcc-arm-none-eabi/bin" && echo $PATH 
          mkdir build -p && cd build && cmake ../program
      - name: Build Hex
        run: |
          PATH="$PATH:/home/runner/work/rm_power_manager/rm_power_manager/gcc-arm-none-eabi/bin" && echo $PATH 
          cd build && cmake --build . --target power_manager.elf -- -j $(nproc) && ls
      - name: Upload Hex
        uses: actions/upload-artifact@v2
        with:
          name: power_manager_hex
          path: build/power_manager.hex
